services:
  java:
    build:
      context:  ../  # 指向 Dockerfile 的父目录
      dockerfile: Dockerfile/Dockerfile  # 指向 Dockerfile 的确切位置
    image: pig4cloud  # 指定镜像名称
    container_name: pig4cloud  # 指定容器名称
    ports:
      - "9000:9000"  # 将容器的9000端口映射到主机的9000端口
    volumes:
      - /home/java/pig4cloud/jar:/app/  # 将本地目录挂载到容器
    networks:
      - network  # 使用共享网络
networks:
  network:  # 创建一个名为 network 的网络
