-- =============================================================
-- V8 移除Flowable审批流：清理审批中心菜单/授权/配置项，DROP全部
-- Flowable引擎表（ACT_/FLW_前缀，由starter自动创建，共几十张）。
-- 由启动器按 sys_schema_version 版本登记自动执行，也可手动 source。
-- 注意：DROP TABLE IF EXISTS 幂等；未列全的残留表可用下面语句自查：
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = DATABASE() AND (table_name LIKE 'ACT\\_%' OR table_name LIKE 'FLW\\_%');
-- =============================================================
SET NAMES utf8mb4;

-- ----------------------------
-- 1. 审批中心菜单与角色授权
-- ----------------------------
DELETE FROM `role_menu` WHERE `menu_id` = 209;
DELETE FROM `sys_menu` WHERE `id` = 209;

-- ----------------------------
-- 2. 审批人配置项
-- ----------------------------
DELETE FROM `sys_config` WHERE `config_key` = 'approval.assignee';

-- ----------------------------
-- 3. Flowable引擎表（流程/IDM/CMMN/DMN/事件注册/表单/内容）
-- ----------------------------
DROP TABLE IF EXISTS
  `ACT_GE_PROPERTY`, `ACT_GE_BYTEARRAY`,
  `ACT_RE_DEPLOYMENT`, `ACT_RE_PROCDEF`, `ACT_RE_MODEL`, `ACT_PROCDEF_INFO`,
  `ACT_RU_EXECUTION`, `ACT_RU_VARIABLE`, `ACT_RU_TASK`, `ACT_RU_IDENTITYLINK`,
  `ACT_RU_JOB`, `ACT_RU_TIMER_JOB`, `ACT_RU_SUSPENDED_JOB`, `ACT_RU_DEADLETTER_JOB`,
  `ACT_RU_HISTORY_JOB`, `ACT_RU_EVENT_SUBSCR`, `ACT_RU_ENTITYLINK`, `ACT_RU_EXTERNAL_JOB`,
  `ACT_RU_ACTINST`, `ACT_RU_FLOWSTATISTICS`,
  `ACT_HI_PROCINST`, `ACT_HI_ACTINST`, `ACT_HI_TASKINST`, `ACT_HI_VARINST`,
  `ACT_HI_DETAIL`, `ACT_HI_IDENTITYLINK`, `ACT_HI_ATTACHMENT`, `ACT_HI_COMMENT`,
  `ACT_HI_ENTITYLINK`,
  `ACT_EVT_LOG`,
  `ACT_ID_GROUP`, `ACT_ID_MEMBERSHIP`, `ACT_ID_USER`, `ACT_ID_INFO`, `ACT_ID_BYTEARRAY`,
  `ACT_ID_PROPERTY`, `ACT_ID_TOKEN`, `ACT_ID_PRIV`, `ACT_ID_PRIV_MAPPING`,
  `ACT_DMN_DEPLOYMENT`, `ACT_DMN_DEPLOYMENT_RESOURCE`, `ACT_DMN_DECISION`,
  `ACT_DMN_HI_DECISION_EXECUTION`,
  `ACT_CMMN_DEPLOYMENT`, `ACT_CMMN_DEPLOYMENT_RESOURCE`, `ACT_CMMN_CASEDEF`,
  `ACT_CMMN_CASE_INST`, `ACT_CMMN_MIL_INST`, `ACT_CMMN_PLAN_ITEM_INST`,
  `ACT_CMMN_SENTRY_PART_INST`,
  `ACT_CMMN_RU_CASE_INST`, `ACT_CMMN_RU_PLAN_ITEM_INST`, `ACT_CMMN_RU_MIL_INST`,
  `ACT_CMMN_RU_SENTRY_PART_INST`, `ACT_CMMN_RU_VARIABLE`, `ACT_CMMN_RU_IDENTITYLINK`,
  `ACT_CMMN_RU_ENTITYLINK`, `ACT_CMMN_RU_JOB`, `ACT_CMMN_RU_TIMER_JOB`,
  `ACT_CMMN_RU_SUSPENDED_JOB`, `ACT_CMMN_RU_DEADLETTER_JOB`, `ACT_CMMN_RU_EXTERNAL_JOB`,
  `ACT_CMMN_RU_HISTORY_JOB`, `ACT_CMMN_RU_ACTINST`,
  `ACT_CMMN_HI_CASE_INST`, `ACT_CMMN_HI_PLAN_ITEM_INST`, `ACT_CMMN_HI_MIL_INST`,
  `ACT_CMMN_HI_ACTINST`, `ACT_CMMN_HI_VARIABLE`, `ACT_CMMN_HI_IDENTITYLINK`,
  `ACT_CMMN_HI_ENTITYLINK`,
  `ACT_CO_CONTENT_ITEM`, `ACT_CO_DATABASECHANGELOG`, `ACT_CO_DATABASECHANGELOGLOCK`,
  `FLW_EV_DATABASECHANGELOG`, `FLW_EV_DATABASECHANGELOGLOCK`,
  `FLW_EVENT_DEPLOYMENT`, `FLW_EVENT_RESOURCE`, `FLW_EVENT_DEFINITION`,
  `FLW_CHANNEL_DEFINITION`, `FLW_EVENT_INSTANCE`,
  `FLW_RU_EVENT_INBOUND`, `FLW_RU_EVENT_OUTBOUND`,
  `FLW_APP_DEPLOYMENT`, `FLW_APP_DEFINITION`, `FLW_APP_RESOURCE`,
  `FLW_DMN_DEPLOYMENT`, `FLW_DMN_DEPLOYMENT_RESOURCE`, `FLW_DMN_DECISION`,
  `FLW_FO_FORM_DEPLOYMENT`, `FLW_FO_FORM_DEFINITION`, `FLW_FO_FORM_RESOURCE`,
  `FLW_FO_FORM_INSTANCE`,
  `FLW_CO_CONTENT_ITEM`, `FLW_CO_FOLDER`,
  `FLW_CHANNEL_DEFINITION`, `FLW_EVENT_INBOUND_INSTANCE`, `FLW_EVENT_OUTBOUND_INSTANCE`;
