-- =============================================================
-- V9 补充清理Flowable引擎表。
-- 背景：V8的一次性DROP TABLE因表间外键约束失败（errno 3730：删被
-- 引用的父表被拒），continueOnError模式吞掉报错后版本已登记不再重跑，
-- 且清单遗漏了ACT_APP_*/FLW_RU_BATCH*/ACT_HI_TSK_LOG等表。
-- 本次：先关外键检查，再DROP（清单以实际存在的70张表为准，均带IF EXISTS幂等）。
-- 由启动器按 sys_schema_version 版本登记自动执行，也可手动 source。
-- =============================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS
  `ACT_APP_APPDEF`, `ACT_APP_DATABASECHANGELOG`, `ACT_APP_DATABASECHANGELOGLOCK`,
  `ACT_APP_DEPLOYMENT`, `ACT_APP_DEPLOYMENT_RESOURCE`,
  `ACT_CMMN_CASEDEF`, `ACT_CMMN_DATABASECHANGELOG`, `ACT_CMMN_DATABASECHANGELOGLOCK`,
  `ACT_CMMN_DEPLOYMENT`, `ACT_CMMN_DEPLOYMENT_RESOURCE`,
  `ACT_CMMN_HI_CASE_INST`, `ACT_CMMN_HI_MIL_INST`, `ACT_CMMN_HI_PLAN_ITEM_INST`,
  `ACT_CMMN_RU_CASE_INST`, `ACT_CMMN_RU_MIL_INST`, `ACT_CMMN_RU_PLAN_ITEM_INST`,
  `ACT_CMMN_RU_SENTRY_PART_INST`,
  `ACT_DMN_DATABASECHANGELOG`, `ACT_DMN_DATABASECHANGELOGLOCK`, `ACT_DMN_DECISION`,
  `ACT_DMN_DEPLOYMENT`, `ACT_DMN_DEPLOYMENT_RESOURCE`, `ACT_DMN_HI_DECISION_EXECUTION`,
  `ACT_EVT_LOG`, `ACT_GE_BYTEARRAY`, `ACT_GE_PROPERTY`,
  `ACT_HI_ACTINST`, `ACT_HI_ATTACHMENT`, `ACT_HI_COMMENT`, `ACT_HI_DETAIL`,
  `ACT_HI_ENTITYLINK`, `ACT_HI_IDENTITYLINK`, `ACT_HI_PROCINST`, `ACT_HI_TASKINST`,
  `ACT_HI_TSK_LOG`, `ACT_HI_VARINST`,
  `ACT_ID_BYTEARRAY`, `ACT_ID_GROUP`, `ACT_ID_INFO`, `ACT_ID_MEMBERSHIP`,
  `ACT_ID_PRIV`, `ACT_ID_PRIV_MAPPING`, `ACT_ID_PROPERTY`, `ACT_ID_TOKEN`, `ACT_ID_USER`,
  `ACT_PROCDEF_INFO`, `ACT_RE_DEPLOYMENT`, `ACT_RE_MODEL`, `ACT_RE_PROCDEF`,
  `ACT_RU_ACTINST`, `ACT_RU_DEADLETTER_JOB`, `ACT_RU_ENTITYLINK`, `ACT_RU_EVENT_SUBSCR`,
  `ACT_RU_EXECUTION`, `ACT_RU_EXTERNAL_JOB`, `ACT_RU_HISTORY_JOB`, `ACT_RU_IDENTITYLINK`,
  `ACT_RU_JOB`, `ACT_RU_SUSPENDED_JOB`, `ACT_RU_TASK`, `ACT_RU_TIMER_JOB`, `ACT_RU_VARIABLE`,
  `FLW_CHANNEL_DEFINITION`, `FLW_EVENT_DEFINITION`, `FLW_EVENT_DEPLOYMENT`,
  `FLW_EVENT_RESOURCE`, `FLW_EV_DATABASECHANGELOG`, `FLW_EV_DATABASECHANGELOGLOCK`,
  `FLW_RU_BATCH`, `FLW_RU_BATCH_PART`;

SET FOREIGN_KEY_CHECKS = 1;
