server:
  port: 9000
spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pigx_admin
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration: OFF
    org.springframework.security: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: OFF
