server:
  port: 9000
spring:
  profiles:
    active: dev  # 默认环境
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration: OFF
#    org.springframework.security: DEBUG
#    org:
#      springframework:
#        boot:
#          autoconfigure: OFF
tomcat:
  max-http-form-post-size: -1


